#!/bin/bash
#nginx installation

# Update package index
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Start Nginx
sudo systemctl start nginx

# Enable Nginx to start on boot
sudo systemctl enable nginx

# Display Nginx status
sudo systemctl status nginx
