#!/bin/bash

# Update package index
sudo apt update

# Install HAProxy
sudo apt install haproxy -y

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Display HAProxy status
sudo systemctl status haproxy
