#!/bin/bash

# Check if password argument is provided
if [ $# -ne 1 ]
then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# MySQL root password
MYSQL_PASSWORD="$1"

# Output directory for backups
BACKUP_DIR="/home/ubuntu/"

# Create a directory for the backup if it doesn't exist
mkdir -p "$BACKUP_DIR"

# Timestamp for the backup file name
TIMESTAMP=$(date +"%d-%m-%Y")

# MySQL dump file name
MYSQL_DUMP_FILE="$BACKUP_DIR/backup.sql"

# Compressed archive name
ARCHIVE_NAME="$BACKUP_DIR/$TIMESTAMP.tar.gz"

# MySQL dump command
mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > "$MYSQL_DUMP_FILE"

# Check if mysqldump was successful
if mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > "$MYSQL_DUMP_FILE"; then
    echo "MySQL dump completed successfully."
else
    echo "Error: MySQL dump failed. Exiting."
    exit 1
fi

# Check if compression was successful
if tar -czvf "$ARCHIVE_NAME" "$MYSQL_DUMP_FILE"; then
    echo "Compression completed successfully."
else
    echo "Error: Compression failed. Exiting."
    exit 1
fi
