#!/usr/bin/env bash
# Fixing Nginx configuration to listen on port 80 and ensure it's running
sudo sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
sudo pkill -f nginx
