#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.
# awk '{print $1 " " $9}' apache-access.log
log_file="apache-access.log"
awk '{print $1, $9}' "$log_file"
